### ISSUE TITLE
Development release tracker 

### ISSUE THREAD

**Issue by cb-Hades** [draeger-lab/SPECIMEN#11]
Release a development version of SPECIMEN of GitHub.

Taks:

- [x] docs
- [x] Set-up readthedocs
- [x] README
- [x] check security options
- [x] add tags
- [x] merge branch into main
- [x] toml version
- [x] Change to public

Notes:

- version format: 0.0.dev0

**Comment by cb-Hades** [comment]
developer release published
