### ISSUE TITLE
Release 1.0.0 Tracker

### ISSUE THREAD

**Issue by cb-Hades** [draeger-lab/SPECIMEN#7]
This issue is for tracking everything that needs to be done before the release of the first version:

## TODO:
- [ ] Documentation -> #5 
- [ ] Installation -> #6 
- ❌  pypi -> currently not possible, as some packages can only be installed via git
- [x] fix HQTB -> #17 
- [x] cleanup CMPB -> #8  
- [x] readthedocs
- [x] integration of refinegems -> #1 
- [x] clean up the gitHub + make it public
- [x] merge the modules of subpackage refinement into one module called refinement (as there are mostly only the `run` functions left after restructuring with refinegems)

## CHECK:
- [ ] FutureWarnings for Pandas 3.0
- [ ] should be working from 3.10 onwards
- [ ] check Todos & co comments in the code, if something was missed
- [ ] TESTING, re-check access points, Python versions and OS-independancy and, of course, the workflows
